name: Databricks Bundle Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # VM from github
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      
      - name: Validate bundle
        run: databricks bundle validate --target test
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          BUNDLE_VAR_my_warehouse_id: ${{ secrets.SQL_WAREHOUSE_ID }}
      
      - name: Deploy Bundle to TEST
        run: |
          databricks bundle deploy --target test
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          BUNDLE_VAR_my_warehouse_id: ${{ secrets.SQL_WAREHOUSE_ID }}

      - name: Run pipeline
        run: databricks bundle run --target test mazhara_pipeline --refresh-all
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          BUNDLE_VAR_my_warehouse_id: ${{ secrets.SQL_WAREHOUSE_ID }}

      - name: Apply RLS and CLS via SQL API
        run: |
          SQL_QUERY=$(cat security_policies.sql | sed ':a;N;$!ba;s/\n/ /g')

        curl -X POST "$DATABRICKS_HOST/api/2.0/sql/statements/" \
          -H "Authorization: Bearer $DATABRICKS_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
            \"statement\": \"$SQL_QUERY\",
            \"warehouse_id\": \"$SQL_WAREHOUSE_ID\"
          }"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          SQL_WAREHOUSE_ID: ${{ secrets.SQL_WAREHOUSE_ID }}